### ISSUE TITLE
Create a snapshot release of OQS-libssh to match liboqs 0.7.2 release

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/libssh#12]
Hi @kevinmkane, should we tag a release of libssh to match the recent liboqs 0.7.2 release?  If so what needs to be done?

**Comment by kevinmkane** [comment]
If this weekend's CI still works, then we can just tag the current branch point and make a release of that. I'll look at this early next week.

**Comment by kevinmkane** [comment]
@dstebila Draft release is up here, please take a look: https://github.com/open-quantum-safe/libssh/releases/tag/untagged-61ad4735eda4fd3aec23

**Comment by kevinmkane** [comment]
@dstebila Check that, URL changed when I made an edit: https://github.com/open-quantum-safe/libssh/releases/tag/untagged-3e7d39a77199f8e9a1a4

**Comment by dstebila** [comment]
> @dstebila Check that, URL changed when I made an edit: https://github.com/open-quantum-safe/libssh/releases/tag/untagged-3e7d39a77199f8e9a1a4

Looks good to me, go ahead. Thanks Kevin!

**Comment by kevinmkane** [comment]
Published. https://github.com/open-quantum-safe/libssh/releases/tag/OQS-libssh-snapshot-2022-08
