### ISSUE TITLE
pkd_hello fails to run with latest liboqs

### ISSUE THREAD

**Issue by kevinmkane** [open-quantum-safe/libssh#16]
https://github.com/open-quantum-safe/libssh/actions/runs/4154336681/jobs/7186653251

Re-enable CI workflow when fixed.

**Comment by dstebila** [comment]
In https://github.com/open-quantum-safe/openssh/commit/46a378c30e107285c1c4fb2aee2e6389c8de0c21, we started disabling by default some of the variants that were not selected by NIST -- e.g., turning off the Dilithium AES variants.  Which appears to be what triggered the failure here.  So the two options for fixing this would be to build a version of OQS-OpenSSH with those variants back on, or turn those variants off here in libssh as well.

**Comment by kevinmkane** [comment]
I expect the correct choice is to turn them off here too and maintain parity with OQS-OpenSSH. There's no expectation a fork where those variants were turned back on will continue to function.
