### ISSUE TITLE
Update hybrid key exchange encoding

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/libssh#18]
As described in https://github.com/open-quantum-safe/openssh/issues/136, the shared secret format for hybrid key exchange in OQS-OpenSSH doesn't match the current IETF Internet-Draft.  Since OQS-libssh uses the same format as OQS-OpenSSH, it also doesn't match the Internet-Draft.  It should be updated, analogous to https://github.com/open-quantum-safe/openssh/pull/137.  

Note that there's still some discussion in https://github.com/open-quantum-safe/openssh/pull/137 about whether to change the hybrid key exchange method names, which might also lead to changes in OQS-libssh.

**Comment by christianpaquin** [comment]
We have two PRs ([137](https://github.com/open-quantum-safe/openssh/pull/137), [138](https://github.com/open-quantum-safe/openssh/pull/138)) in openssh ready for merge to stay in compliance with the spec. These changes should be adopted in this project also. FYI, @kevinmkane.

**Comment by kevinmkane** [comment]
@christianpaquin I think I've got changes to match open-quantum-safe/openssh#137 and open-quantum-safe/openssh#138. I'd say go ahead with merging those if you're ready, and that will make my CI pick up those as latest when I open a PR here.

**Comment by christianpaquin** [comment]
Great thanks; I'll go ahead and merge.
